name: music_player_api
description: A dart API client for the music player API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_vlc: ^0.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  items_repository:
    path: ../items_repository
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  just_audio: ^0.9.37
  rxdart: ^0.27.7
  sqlite_database:
    path: ../sqlite_database

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  pedantic: ^1.11.1
  analyzer: ^6.4.1
