name: jellyflut_models
description: All models that app needs
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  device_info_plus: ^10.1.0
  drift: ^2.17.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  meta: ^1.11.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  pedantic: ^1.11.1
  build_web_compilers: ^4.0.10
  drift_dev: ^2.17.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  analyzer: ^6.4.1
