name: live_tv_api
description: A dart API client for the Jellyfin Live TV API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  pedantic: ^1.11.1
