name: streaming_repository
description: A repository that handles streaming related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  better_player_plus: ^1.0.6
  dart_vlc: ^0.4.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.4.1
  freezed_annotation: ^2.4.1
  items_api:
    path: ../items_api
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  # Primary package.
  media_kit: ^1.1.10+1
  # For video rendering.
  media_kit_video: ^1.2.4
  # Android package for video native libraries.
  media_kit_libs_android_video: ^1.3.6
  # iOS package for video native libraries.
  media_kit_libs_ios_video: ^1.1.4
  # macOS package for video native libraries.
  media_kit_libs_macos_video: ^1.1.4
  # Windows package for video native libraries.
  media_kit_libs_windows_video: ^1.0.9
  # GNU/Linux dependency package.
  media_kit_libs_linux: ^1.1.3
  sqlite_database:
    path: ../sqlite_database
  streaming_api:
    path: ../streaming_api
  video_player: ^2.8.6
  window_manager: ^0.3.8
  youtube_explode_dart: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  pedantic: ^1.11.1
  analyzer: ^6.4.1
