name: downloads_api
description: The interface and models for an API providing access to downloads.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  meta: ^1.11.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  analyzer: ^6.4.1
